jobs:
  - name: show-branch
    plan:
      - get: source
        trigger: true
      - task: show-head-commit
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: bitnami/git }
          inputs: [ name: source ]
          run:
            path: bash
            args:
              - -c
              - |
                cd source
                git show
resources:
  - name: source
    type: git
    source:
      uri: https://github.com/suhlig/concourse-rss-resource
      password: ((github.access_token))
      branch: ((branch))
